# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wd < Formula
  desc ""
  homepage ""
  version "1.2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/onsd/wd/releases/download/v1.2.0/wd_1.2.0_darwin_amd64.tar.gz"
    sha256 "70f0ee8cbfe7732b410f184d16289406a5176f0fe9ff61bd42ca298ac7d23d43"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/onsd/wd/releases/download/v1.2.0/wd_1.2.0_linux_amd64.tar.gz"
    sha256 "9665faeceabe926c6d41b2932e915082d79ebbe0e16bc22d3573de98d616b13f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/onsd/wd/releases/download/v1.2.0/wd_1.2.0_linux_arm64.tar.gz"
    sha256 "08063730f24ccac3f5cf41e2b99b44d3d6513bd87daa9e404d879ba300270ca9"
  end

  def install
    bin.install "wd"
  end
end
